server:
  port: 9090

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: gaslab
    password: 1234
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
